export type ReminderTone =
  | "formal"
  | "softie"
  | "sarcastic"
  | "mystic";

export type ReminderEvent =
  | "overdue_or_taking_long"
  | "finished_on_time"
  | "finished_late";

export type ReminderTemplateGroups = {
  overdue_or_taking_long: string[];
  finished_on_time: string[];
  finished_late: string[];
};

export type NotificationTemplates = Record<ReminderTone, ReminderTemplateGroups>;

export const NOTIFICATION_TEMPLATES: NotificationTemplates = {
  "formal": {
    "overdue_or_taking_long": [
      "Your task needs attention.",
      "This task is still pending.",
      "You planned this task, but it has not been completed yet.",
      "This task is taking longer than expected.",
      "Your task has passed its expected time.",
      "This is a reminder to return to your task.",
      "The task is still open.",
      "Your planned work has not been finished.",
      "This task may need to be restarted or rescheduled.",
      "Your progress is behind the expected timing.",
      "This task is now overdue.",
      "The expected completion time has passed.",
      "Please review this task when you can.",
      "This task has been waiting longer than planned.",
      "Your schedule shows this task still incomplete.",
      "This item is still unresolved.",
      "Your task remains active.",
      "This task is still waiting for completion.",
      "The task duration has exceeded the estimate.",
      "This task requires follow-up.",
      "You may want to continue or update this task.",
      "This task is no longer on schedule.",
      "Your planned task is delayed.",
      "This task has not moved forward yet.",
      "This item is still in your active list.",
      "The task has exceeded its planned window.",
      "This is a reminder to check your task status.",
      "Your task has not been marked complete.",
      "This task is still open after the planned time.",
      "Your task is delayed.",
      "The expected time for this task has passed.",
      "This task needs your decision: continue, pause, or reschedule.",
      "Your task timing needs review.",
      "This task has stayed pending longer than expected.",
      "Please return to this task or adjust the plan.",
      "The task is not complete yet.",
      "Your task is still waiting for action.",
      "This task remains unfinished.",
      "The task has passed its planned completion point.",
      "This task needs attention before it falls further behind.",
      "Your current task is running over time.",
      "This task may need a new estimate.",
      "Your task is behind schedule.",
      "This task is still not done.",
      "The task remains incomplete after the expected time.",
      "This task should be reviewed now.",
      "Your task has been pending for a while.",
      "This reminder is here because the task is still incomplete.",
      "Your planned task has not been closed.",
      "This task needs either progress or rescheduling."
    ],
    "finished_on_time": [
      "Task completed on time.",
      "You completed the task as planned.",
      "Good work. The task was finished on schedule.",
      "Task finished within the expected time.",
      "You stayed on track with this task.",
      "The task was completed before it became overdue.",
      "Nice work. The task is complete.",
      "You finished this task on time.",
      "This task was handled as planned.",
      "Completion recorded on schedule.",
      "You met the task timing.",
      "Task closed successfully.",
      "You completed the work within the planned window.",
      "Good progress. Task finished on time.",
      "This task was completed without delay.",
      "You kept this task on schedule.",
      "Task done within estimate.",
      "The task was completed at the right time.",
      "You followed through on this task.",
      "Task completed before the deadline.",
      "This task did not fall behind.",
      "Good timing. Task complete.",
      "You completed the item successfully.",
      "The task has been finished as expected.",
      "On-time completion recorded."
    ],
    "finished_late": [
      "Task completed late.",
      "You finished the task after the planned time.",
      "The task is complete, but it was delayed.",
      "Completion recorded after the expected time.",
      "You finished this task later than planned.",
      "The task was completed after becoming overdue.",
      "Late completion recorded.",
      "Task closed after the scheduled time.",
      "The task took longer than expected, but it is complete.",
      "You completed the task despite the delay.",
      "This task finished behind schedule.",
      "Task completed after the planned window.",
      "You resolved the task late.",
      "The task was delayed, then completed.",
      "Completion happened after the deadline.",
      "The task is no longer open, but it was late.",
      "You finished it after the expected time.",
      "The delay is recorded, but the task is done.",
      "Task completion recorded with lateness.",
      "You completed the task after a delay.",
      "Late, but finished.",
      "The task was overdue before completion.",
      "You recovered the task after it slipped.",
      "The task was completed outside the planned time.",
      "Finished late, but closed successfully."
    ]
  },
  "softie": {
    "overdue_or_taking_long": [
      "Small reminder: this task is still waiting for you.",
      "Hey, this one slipped a little. You can still come back to it.",
      "This task is taking longer than planned, but that is okay. One step now.",
      "Gentle poke: your task is still open.",
      "You have not finished this yet. No panic, just a reminder.",
      "This task is overdue, but you can still save the day.",
      "Your task is waiting patiently.",
      "Little nudge: maybe return to this when you can.",
      "This task needs a tiny bit of attention.",
      "You are behind, but not doomed.",
      "Come back to this task before it grows teeth.",
      "This one is still hanging around.",
      "You can restart with one small action.",
      "This task has been waiting, but it is still manageable.",
      "Soft reminder: future-you would appreciate a little progress.",
      "This task is asking very politely to be noticed.",
      "Not perfect timing, but progress still counts.",
      "You can still turn this around.",
      "This task is late, but not lost.",
      "Take a breath, then give this task one small push.",
      "You do not need to finish everything right now. Just restart.",
      "This task is overdue. Be kind to yourself and do the next step.",
      "Your plan slipped. That happens. Try again.",
      "Little accountability fairy says: please look at the task.",
      "Your task is still there, but so is your chance to finish it.",
      "Not done yet, but still doable.",
      "One tiny step would count here.",
      "This task has waited long enough. Gently, go touch it.",
      "You can do this without making it a whole emotional saga.",
      "This is your friendly reminder, not a trial.",
      "Your task is late, but you are allowed to recover.",
      "Maybe give this task five minutes and see what happens.",
      "Soft poke: it is time to check on this.",
      "This task is becoming a little too comfortable here.",
      "You are not failing. You are just delayed.",
      "Come back when you can, but maybe make that now.",
      "This task is asking for a small rescue mission.",
      "Pause the guilt. Start the task.",
      "It is okay to be late. It is better to continue.",
      "This one still matters, even if it slipped.",
      "Your task is overdue. Your comeback is available.",
      "Just open it. That is the first win.",
      "This task is waiting, and honestly it believes in you.",
      "You can be late and still be proud of finishing.",
      "Please give this task a little attention.",
      "Your schedule got messy. That is human. Continue.",
      "The task is not angry, just disappointed in a cute way.",
      "You can finish this in smaller pieces.",
      "This is a gentle reminder to stop avoiding the tiny monster.",
      "Return to this task before it becomes tomorrow's problem."
    ],
    "finished_on_time": [
      "Nice, you finished it on time.",
      "Look at you staying on track.",
      "That was smooth. Good job.",
      "Task done right on time.",
      "You planned it and actually did it. Lovely.",
      "On time and everything. Proud of you.",
      "That task did not even get a chance to haunt you.",
      "Good work. You kept the promise to yourself.",
      "This was responsible behavior. Very cute.",
      "Task complete. Your future self is smiling.",
      "You handled this before it became stressful.",
      "That is a clean little win.",
      "Done on time. Beautiful.",
      "You kept it simple and finished it.",
      "Nice timing. No drama needed.",
      "That went exactly how it should.",
      "Task completed before it could become a problem.",
      "You did the thing. Soft applause.",
      "This is what calm productivity looks like.",
      "Good job staying ahead.",
      "You finished without turning it into a side quest.",
      "That was a tiny act of self-respect.",
      "Done on time. We love to see it.",
      "This task has been peacefully released.",
      "You showed up and finished. Nice."
    ],
    "finished_late": [
      "Late, but done. That still counts.",
      "You finished it after the delay. Proud of the comeback.",
      "The task took longer, but you still closed it.",
      "Not on time, but not abandoned.",
      "Late finish, real progress.",
      "You came back to it, and that matters.",
      "This was delayed, but you did not give up.",
      "Finished late. Future-you still says thank you.",
      "The timing slipped, but the task is done.",
      "You recovered this one. Good job.",
      "Late does not erase the effort.",
      "This task had a detour, but it got finished.",
      "You made it through the delay.",
      "Done late, but done honestly.",
      "The task waited, and you came back.",
      "This was not perfect, but it was completed.",
      "Late completion. Still a win.",
      "You closed the loop, even after avoiding it.",
      "This task took the scenic route.",
      "You finished it eventually, and eventually is better than never.",
      "Good job bringing this back from the procrastination pile.",
      "The delay happened. The finish still matters.",
      "You did it late, but you did it.",
      "Late, slightly dramatic, but complete.",
      "That task survived the delay and still got done."
    ]
  },
  "sarcastic": {
    "overdue_or_taking_long": [
      "This task has been waiting so long it may start charging rent.",
      "You said later. Later brought receipts.",
      "This 5-minute task is entering its villain era.",
      "The task called. It wants to know if you still work here.",
      "Bold strategy: ignoring the thing you added yourself.",
      "This task has developed lore.",
      "Your procrastination is becoming a case study.",
      "This task is now vintage.",
      "The task is not done, but the excuses are thriving.",
      "You and this task are in a long-term situationship.",
      "This task has been sitting here very professionally doing nothing.",
      "Congratulations, the task is now emotionally attached.",
      "The deadline passed. The task noticed.",
      "This task has survived longer than your motivation.",
      "Still not done? Fascinating commitment to the bit.",
      "The task is overdue and somehow still more patient than me.",
      "You made a todo list and then ghosted it. Iconic.",
      "This task has seen seasons change.",
      "At this point, the task deserves a name.",
      "You are not avoiding it. You are curating suspense.",
      "This task is aging like milk.",
      "Your task is giving abandoned side quest energy.",
      "The task remains unfinished. The drama remains fresh.",
      "This is not a reminder. It is an intervention with buttons.",
      "You have unlocked: Advanced Avoidance.",
      "The task has been pending long enough to learn your habits.",
      "Future-you has filed a complaint.",
      "This task is becoming part of the furniture.",
      "The task is still here. Very loyal. Very concerning.",
      "Your schedule is crying quietly.",
      "This overdue task is now a personality trait.",
      "The task did not complete itself. Rude of it, honestly.",
      "You delayed this so hard it got character development.",
      "The task has entered the witness protection program.",
      "You know what would be funny? Finishing it.",
      "This task is looking at you through the window.",
      "Still pending. Still judging.",
      "Your todo list is starting to sound sarcastic without me.",
      "This task has been ignored with impressive consistency.",
      "The task is overdue. Shocking absolutely no one.",
      "You have postponed this into a whole subplot.",
      "The task is no longer a task. It is a haunting.",
      "You and responsibility are playing hide and seek. Responsibility is winning.",
      "This task has been waiting since the ancient era of 'later'.",
      "This is your sign to stop negotiating with a checkbox.",
      "The task is late, and your excuses are punctual.",
      "Your task is begging for closure.",
      "This task has moved from 'quick thing' to 'emotional burden'.",
      "The procrastination goblin is winning. Fight back.",
      "This task is still undone, which is a choice. A loud one."
    ],
    "finished_on_time": [
      "Look at you, functioning.",
      "Task completed. Society may recover.",
      "You did the thing before it became a tragedy.",
      "On time? Suspiciously responsible.",
      "This task got handled with zero unnecessary lore.",
      "Done on time. Who are you and what have you done with the user?",
      "The checkbox never saw it coming.",
      "Efficiency detected. Rare but appreciated.",
      "You finished it before the panic arc. Impressive.",
      "Task complete. No haunting required.",
      "That was almost too competent.",
      "You beat the deadline. The deadline is embarrassed.",
      "Responsible behavior has been witnessed.",
      "You completed it on time. The app is confused but proud.",
      "Clean execution. Minimal drama. Strange.",
      "You actually followed the plan. Historic.",
      "Done before it became a personality flaw.",
      "This task got absolutely handled.",
      "On-time completion. Nature is healing.",
      "Task finished. Procrastination goblin denied.",
      "You did not let this become tomorrow's problem. Wild.",
      "The task is done and your future self is less annoyed.",
      "This was shockingly efficient.",
      "Well done. The task has been defeated.",
      "You completed it without making it a saga. Respect."
    ],
    "finished_late": [
      "Late, but finally released from captivity.",
      "You finished it after only one dramatic lifetime.",
      "Task completed. The delay will be remembered.",
      "Late, but the checkbox has been fed.",
      "You defeated the task eventually. Emphasis on eventually.",
      "The task is done. The timeline is questionable.",
      "Completed late, because apparently suspense was required.",
      "Better late than haunting your list forever.",
      "Done after a generous procrastination arc.",
      "The task survived neglect and still got closure.",
      "Late finish. Bold pacing choice.",
      "You completed it after giving it a full character arc.",
      "This task is done, despite your best avoidance efforts.",
      "Finished late. The goblin lost in overtime.",
      "The task is complete. The deadline is not impressed.",
      "You did it late, but at least the saga ended.",
      "Late, dramatic, but complete.",
      "This task aged significantly before completion.",
      "Completed after marinating in guilt.",
      "The task is finally free.",
      "You turned a task into a trilogy, but it is done.",
      "Late completion unlocked.",
      "Not punctual, but technically victorious.",
      "You finished it after the deadline left the chat.",
      "The task is done. The procrastination documentary is cancelled."
    ]
  },
  "mystic": {
    "overdue_or_taking_long": [
      "The task spirit grows restless.",
      "This quest has lingered beyond its appointed hour.",
      "A tiny goblin is now guarding this unfinished task.",
      "The hourglass has emptied, yet the task remains.",
      "The prophecy said you would finish this earlier.",
      "This task has crossed into the realm of overdue.",
      "The productivity fairies are tapping their tiny watches.",
      "Your quest marker is glowing aggressively.",
      "The task has become a cursed relic on your list.",
      "Time has passed. The task remains enchanted and unfinished.",
      "The goblin of delay has claimed this task.",
      "This unfinished quest now carries dramatic energy.",
      "The calendar spirits are whispering your name.",
      "This task is gathering dust in the enchanted forest of later.",
      "A deadline rune has cracked.",
      "The task has awakened. It demands tribute.",
      "You have angered the small gods of scheduling.",
      "The task waits at the edge of the swamp of avoidance.",
      "The quest is overdue, brave traveler.",
      "Your task has turned into a tiny dragon.",
      "The moon has changed, and still this task remains.",
      "The ancient scroll says: please finish the thing.",
      "The portal to 'later' is closing.",
      "This task has been cursed by postponement magic.",
      "The goblin council has noticed your delay.",
      "The task has started glowing red on the map.",
      "Your quest log is judging you in elvish.",
      "The spell of procrastination is getting stronger.",
      "This task has become a haunted checkbox.",
      "The forest whispers: stop avoiding it.",
      "The task has wandered into the forbidden lands of overdue.",
      "The deadline bell has rung in the distance.",
      "Your task is now protected by a procrastination troll.",
      "The stars suggest immediate action.",
      "This task has become a side quest with consequences.",
      "The oracle saw this coming. She is tired.",
      "The task has been waiting since the age of 'soon'.",
      "A small cursed frog now represents this unfinished item.",
      "The task is overdue. The goblins are celebrating.",
      "Your todo scroll has darkened around this task.",
      "The task dragon grows larger each hour.",
      "The fairy of responsibility is hovering nearby.",
      "This quest remains incomplete, and the kingdom is mildly concerned.",
      "The deadline ghost has entered the room.",
      "The task has passed through the mist of neglect.",
      "Your task is now humming with unfinished magic.",
      "The realm demands progress.",
      "The goblin king asks why this is still open.",
      "This task has become a magical burden.",
      "The spell can be broken only by starting."
    ],
    "finished_on_time": [
      "The quest is complete, right on time.",
      "The task dragon has been defeated before sunset.",
      "The productivity fairies approve.",
      "You completed the quest before the curse could form.",
      "The checkbox has been blessed.",
      "The hourglass smiles upon you.",
      "Task completed. The realm is safe.",
      "The prophecy was fulfilled on schedule.",
      "The goblin of delay has been banished.",
      "You finished before the deadline moon rose.",
      "A clean victory, brave traveler.",
      "The task spirit is at peace.",
      "The scroll has been sealed successfully.",
      "Your quest log shines brighter now.",
      "The tiny scheduling gods nod respectfully.",
      "The deadline dragon never stood a chance.",
      "You completed the ritual on time.",
      "The task has returned to dust and peace.",
      "The fairy council grants one small applause.",
      "The enchanted checkbox has been conquered.",
      "The realm records your punctual victory.",
      "Your timing magic was strong today.",
      "The task was completed before chaos arrived.",
      "The quest ended without a curse. Rare blessing.",
      "You have earned one responsible little sparkle."
    ],
    "finished_late": [
      "The quest is complete, though the moon has long risen.",
      "Late, but the curse is broken.",
      "The task dragon has finally been defeated.",
      "The checkbox ghost may now rest.",
      "The prophecy was delayed, but fulfilled.",
      "The goblin of procrastination has been pushed back.",
      "Your quest ended after a long detour through the swamp.",
      "The task is done. The realm exhales.",
      "Late completion, but the magic still counts.",
      "The scroll is sealed after some dramatic delay.",
      "The task spirit has been released at last.",
      "You returned from the forest of later with proof of work.",
      "The deadline ghost grumbles, but accepts your offering.",
      "The task was late, but the kingdom survives.",
      "The curse weakened once you finished.",
      "The goblin council is disappointed by your recovery.",
      "The task dragon fell eventually.",
      "Your timing was cursed, but your finish was real.",
      "The quest took the scenic enchanted route.",
      "Late, but victorious under a questionable moon.",
      "The checkbox has been freed from its tiny prison.",
      "The spell of avoidance has been broken.",
      "The task is complete after wandering through chaos.",
      "The realm forgives the delay. Mostly.",
      "The quest is done. The goblins are annoyed."
    ]
  }
} as const;

export function getNotificationReplies(
  tone: ReminderTone,
  event: ReminderEvent,
): readonly string[] {
  return NOTIFICATION_TEMPLATES[tone][event];
}

export function getRandomNotificationReply(
  tone: ReminderTone,
  event: ReminderEvent,
): string | null {
  const replies = getNotificationReplies(tone, event);

  if (replies.length === 0) {
    return null;
  }

  const randomIndex = Math.floor(Math.random() * replies.length);
  return replies[randomIndex] ?? null;
}
